name: 100% Guaranteed App Store AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 4. Install Cordova
        run: npm install -g cordova

      - name: 5. THE MAGIC STEP (Build & Sign AAB)
        run: |
          echo "==== STARTING PROJECT ===="
          cordova create mygame com.vinay.myapp "Test Pro"
          
          echo "==== COPYING FILES ===="
          cp config.xml mygame/
          cp index.html mygame/www/
          
          cd mygame
          
          echo "==== ADDING ANDROID 13 ===="
          cordova platform add android@13.0.0
          
          echo "==== BUILDING APP BUNDLE (.aab) ===="
          cordova build android --release
          
          echo "==== GENERATING KEYSTORE (CHABHI) ===="
          keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Vinay, OU=Dev, O=App, L=City, S=State, C=IN" -storepass 12345678 -keypass 12345678
          
          echo "==== SIGNING .AAB FILE ===="
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore my-release-key.keystore platforms/android/app/build/outputs/bundle/release/app-release.aab alias_name -storepass 12345678
          
          echo "==== RENAMING FINAL FILE ===="
          mv platforms/android/app/build/outputs/bundle/release/app-release.aab platforms/android/app/build/outputs/bundle/release/Final-PlayStore-Ready.aab
          echo "==== SUCCESS!!! ===="

      - name: 6. Upload Final App and Keystore
        uses: actions/upload-artifact@v4
        with:
          name: App-and-Keystore
          path: |
            mygame/platforms/android/app/build/outputs/bundle/release/Final-PlayStore-Ready.aab
            mygame/my-release-key.keystore
