name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create and Build
        run: |
          # 1. Project setup
          rm -rf myapp
          cordova create myapp com.vinay.myapp "TestPro"
          
          # 2. Files copy
          [ -f index.html ] && cp index.html myapp/www/index.html
          [ -f config.xml ] && cp config.xml myapp/config.xml
          
          cd myapp
          cordova platform add android@13.0.0
          
          # 3. Build Release
          cordova build android --release --no-telemetry
          
          # 4. APK ko dhund kar Main Folder mein lana (Ye sabse zaroori hai)
          cd ..
          mkdir -p output_apk
          find myapp/platforms/android/app/build/outputs/apk/ -name "*.apk" -exec cp {} output_apk/ \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-App-Release-Final
          # Ab hum sirf is folder ko upload karenge jisme humne file copy ki hai
          path: output_apk/*.apk
          if-no-files-found: error
